apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poller
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/dev/poller
    repoURL: https://github.com/FKouhai/rss-demo-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
