apiVersion: v1
data:
  config.json: '{"rss_feeds":["https://feeds.arstechnica.com/arstechnica/index","https://www.reddit.com/r/kubernetes/.rss","https://determinate.systems/rss.xml"]}'
kind: ConfigMap
metadata:
  name: poller-config
  namespace: demo
