apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: poller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poller
    spec:
      containers:
        - env:
            - name: NOTIFICATION_SENDER
              value: http://notify.demo.svc.cluster.local:3000/push
            - name: OTEL_EP
              value: signoz-otel-collector.signoz.svc.cluster.local:4317
            - name: NOTIFICATION_ENDPOINT
              value: https://discord.com/api/webhooks/1433874286921253005/2g9_U5BsPm-YUB0fdx4vaqmhV_mz-VHwOYBabV5ZGjHXggwTC_4jbh1uuTdg7WHyxcXN
          image: ghcr.io/fkouhai/rss_poller-x86_64-linux:0.1.7
          imagePullPolicy: IfNotPresent
          name: poller
      securityContext:
        fsGroup: 1000
