apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: poller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poller
    spec:
      containers:
        - env:
            - name: NOTIFICATION_ENDPOINT
              value: http://notify.demo.cluster.svc.local:3000/push
            - name: OTEL_EP
              value: ""
            - name: NOTIFICATION_SENDER
              value: https://discord.com/api/webhooks/1400936674522828892/rEYQaa9DRY9pKse9YPT4XjWQmDOd6gARpp6OdYU27icRoucGCkGs3zhdlxhNuOucSiSZ
          image: ghcr.io/fkouhai/rss_poller-x86_64-linux:0.0.4
          imagePullPolicy: IfNotPresent
          name: poller
      securityContext:
        fsGroup: 1000
