apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - env:
            - name: POLLER_ENDPOINT
              value: http://poller.demo.svc.cluster.local:3000/rss
          image: ghcr.io/fkouhai/rss_frontend-x86_64-linux:0.1.4
          imagePullPolicy: IfNotPresent
          name: frontend
      securityContext:
        fsGroup: 1000
