apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: fkouhailabs
  name: frontend
  namespace: demo
spec:
  rules:
    - host: rss.fkouhailabs.net
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 4321
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - rss.fkouhailabs.net
      secretName: rss-http-tls
