apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notify
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notify
    spec:
      containers:
        - env:
            - name: OTEL_EP
              value: signoz-otel-collector.signoz.svc.cluster.local:4317
          image: ghcr.io/fkouhai/rss_notify-x86_64-linux:0.1.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          name: notify
      securityContext:
        fsGroup: 1000
